language: java
jdk:
      - oraclejdk8

before_deploy:
      - zip -r latest *
      - mkdir -p dpl_cd_upload
      - mv latest.zip dpl_cd_upload/latest.zip

deploy:
      - provider: s3
        access_key_id: AKIAIU3BPZCVBLDO3RKA
        secret_access_key: &1
            secure: D8cEbP62uS6OPH0mwziOHbUbPI3Bp9Sk2mgptoBLNwCLlpQqq6pudeaBjMgaPRpv3P0YuzLIEnt8xNSdql+mnSeBeEsHneQBHh3VsX1MQU6WRacon5h/ddNTPx3dRZyMmD8IPLDLGkTEOCQhcacQwXcTPBT0QZBly9eb5uT+NbHsfrkOTc/u70Id0ZZeFF4RkIhiuKq464QiP2Z5IVTGUKplwhpty/3QRriZo7FYqn5BVFkl6Kw/ts5Ckmztx6ypdbXDgz2igLcgdZ6jyjyBd1vAZqIJd5CWGicL49QustcP0Ny11gAJqJpH05Df4L3iwpsYHgO/e/6IpxsRlWAa/IEITsvBcjeDNcUbu4VWR8TZRALGEdKSm3KYiTBwqrkbLsOy9/IiCAUQcNyrXnt4HO5vzjFI530WSK1iFSUqZOmF/923GaKpGTXznReB7KakcHt6mWJtP1uTRiIXE3OnW+o0reecFyl3TQh9zoUuqWZbW5GXZcBQelLYhd7VQIx/BbPcxlJf5pmK6+0NqAfRQBW3aHg3tJ++qNBM0tCKcABW9fpPH+VFYISetRufySmdJu3TMDxQQGvlzIKnxStQR1sP0Y0IZLUCsInfKy1rwGmAraUMKz6KzjT/tkTaO/tSkvM8CAoeszwK55mW/X2P2aVzmhfcJYPMnKUKktbXyyg=
        local_dir: dpl_cd_upload
        skip_cleanup: true
        on: &2
            repo: weili6/neu-csye6225-4
        bucket: code-deploy.neu-csye6225-spring2017-team-4.me    
      - provider: codedeploy
        access_key_id: AKIAIU3BPZCVBLDO3RKA
        secret_access_key: *1
        bucket: code-deploy.neu-csye6225-spring2017-team-4.me
        key: latest.zip
        bundle_type: zip
        application: jobportal
        deployment_group: MyDeploymentGroup
        on: *2
