language: java
jdk:
      - oraclejdk8

sudo: false
install: true

script:
  - ./mvnw package


after_success:
  - mkdir -p codedeploy
  - zip -r jobportal.zip target/team4-0.0.1-SNAPSHOT.war appspec.yml restartapp.sh
  - mv jobportal.zip codedeploy/
  - cd codedeploy


before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIN7HR5MN3A7QDUEQ
    secret_access_key: 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
    local_dir: codedeploy
    bucket: code-deploy.neu-csye6225-spring2017-team-4.me
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAIN7HR5MN3A7QDUEQ
    secret_access_key: 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
    bucket: code-deploy.neu-csye6225-spring2017-team-4.me
    key: jobportal.zip
    bundle_type: zip
    application: jobportal
    deployment_group: jobportal
    region: us-east-1
    wait-until-deployed: true
    
