language: java
jdk:
      - oraclejdk8

sudo: false
install: true

script:
  - ./mvnw package


after_success:
  - mkdir -p codedeploy
  - zip -r jobportal.zip target/team4-0.0.1-SNAPSHOT.war appspec.yml restartapp.sh
  - mv jobportal.zip codedeploy/
  - cd codedeploy


before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIN7HR5MN3A7QDUEQ
    secret_access_key:
      secure: "mBovKA2dJouXIBuTQIviT6QbN5WS2PJijAKgk7fg4sS5/UUk/YMjaAzaXoD+R9Hr4HXs9qQWJV/DPuD2UUWlxMMCt02N+2qJE7FbCujdhxY3CLVA0FDIx2j8NV65xZsg4sg0GlKIWGF50C6FVXmYBDrat6IKRkpP9soevCn35+dFvtDmZK9s7uitl+OgtT2Mfx6SmutCLfCSBZMNbdbhStOtJE3ryIO7Eu6v60LGfGZKH7uTL6dVQWP47wTN4ufjKAzfMkWOg3+WUO9r7IMyvmBtKyHinrBDYMY2sWIufAfGkDtwJLaxoZPW5tpQUjQfHGKMg/K4qUU+SKXFIThkqdAxdwd0+PSfCw4CFayg+xshRqfrGzSNzP9LzlICxIxY3K5bDsDYbCWK+C0BoSNtVtKgPCd3nIg0ociVO3sKHgzwWlXsNQ98ztlqn+sDC/G3qWf+hrHadrvdf0PMNVDwjDYOTatbZeq4w6KHKrcsogQE8WC3PVIMy9RJoVRGO3nlF0vEfvdgTroHbhgRcM6wwkGM8HbAdNp9WWJhU2bDek0mjjyHzxGgyrryWezm7VE9Sb6RoRI8eu5pKoyUVJzUMvncrD4StOF3uIfgCh+z6TESpQ8lryvdTQp4LM1kV1qQCdU0a28lfo8/wJxmHuHG7GqjSGQOe6hrqIE8pqlFV0o="
    local_dir: codedeploy
    bucket: code-deploy.neu-csye6225-spring2017-team-4.me
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAIN7HR5MN3A7QDUEQ
    secret_access_key: 
      secure: "mBovKA2dJouXIBuTQIviT6QbN5WS2PJijAKgk7fg4sS5/UUk/YMjaAzaXoD+R9Hr4HXs9qQWJV/DPuD2UUWlxMMCt02N+2qJE7FbCujdhxY3CLVA0FDIx2j8NV65xZsg4sg0GlKIWGF50C6FVXmYBDrat6IKRkpP9soevCn35+dFvtDmZK9s7uitl+OgtT2Mfx6SmutCLfCSBZMNbdbhStOtJE3ryIO7Eu6v60LGfGZKH7uTL6dVQWP47wTN4ufjKAzfMkWOg3+WUO9r7IMyvmBtKyHinrBDYMY2sWIufAfGkDtwJLaxoZPW5tpQUjQfHGKMg/K4qUU+SKXFIThkqdAxdwd0+PSfCw4CFayg+xshRqfrGzSNzP9LzlICxIxY3K5bDsDYbCWK+C0BoSNtVtKgPCd3nIg0ociVO3sKHgzwWlXsNQ98ztlqn+sDC/G3qWf+hrHadrvdf0PMNVDwjDYOTatbZeq4w6KHKrcsogQE8WC3PVIMy9RJoVRGO3nlF0vEfvdgTroHbhgRcM6wwkGM8HbAdNp9WWJhU2bDek0mjjyHzxGgyrryWezm7VE9Sb6RoRI8eu5pKoyUVJzUMvncrD4StOF3uIfgCh+z6TESpQ8lryvdTQp4LM1kV1qQCdU0a28lfo8/wJxmHuHG7GqjSGQOe6hrqIE8pqlFV0o="
    bucket: code-deploy.neu-csye6225-spring2017-team-4.me
    key: jobportal.zip
    bundle_type: zip
    application: jobportal
    deployment_group: jobportal
    region: us-east-1
    wait-until-deployed: true
    
