version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartapp.sh
    destination: /home/ubuntu
  - source: ./target/team4-0.0.1-SNAPSHOT.war
    destination: /home/ubuntu

#permissions:
#  - object: /var/lib/tomcat7/webapps
#      pattern: "**"
#      owner: tomcat7
#      group: tomcat7
#      mode: 755
#      type:
#        - directory
#  - object: /home/ubuntu
#      pattern: "*.sh"
#      owner: ubuntu
#      mode: 755
#      type:
#        - file

hooks:
  AfterInstall:
   - location: /home/ubuntu/restartapp.sh
     timeout: 180
     runas: ubuntu
